#!/bin/bash

set -euf -o pipefail

# cf. https://github.com/coredns/coredns/README.md

docker run --rm -i -t -v $PWD:/go/src/github.com/coredns/coredns \
      -w /go/src/github.com/coredns/coredns golang:1.12 make
