#!/bin/bash

set -euf -o pipefail

# preload some images
for img in \
  bullseye_me_sudo \
  bullseye_krb5 \
  bullseye_krb5_pg_pipenv_code \
  bullseye_krb5_x11 \
  bullseye_krb5_x11_openjdk8 \
  bullseye_krb5_firefox \
  bullseye_cfssl
do
  docker pull ${REGISTRY:-rg1.tony.wuersch.name:443}/$img
done
docker pull sameersbn/squid:3.5.27-1
