#!/bin/bash

set -euf -o pipefail

. ${0%/*}/script_env

d=$(date +%s)

# rm_all
$REPO_DIR/bin/rm_all > ~/log/rm.$d.out 2>&1 

# build_all
$REPO_DIR/bin/build_all > ~/log/build.$d.out 2>&1 

# push_all
$REPO_DIR/bin/push_all > ~/log/push.$d.out 2>&1 
