#! /bin/bash

set -euf -o pipefail

DOCKER_BRIDGE=my-bridge
# BRIDGE_IP="$(docker inspect $DOCKER_BRIDGE | jq -r '.[0].IPAM.Config[0].Gateway')"
BRIDGE_IP="172.20.0.1"

# number of file descriptors per process
NOFILE=$(ulimit -n)

docker run \
  --detach \
  --restart=always \
  --name squid \
  --ulimit nofile=${NOFILE}:${NOFILE} \
  --publish $BRIDGE_IP:3128:3128/tcp \
  --volume ~/docker/volumes/squid/etc/squid/squid.conf:/etc/squid/squid.conf \
  --volume ~/docker/volumes/squid/log:/var/log/squid \
  --volume ~/docker/volumes/squid/cache:/var/spool/squid \
  sameersbn/squid:3.5.27-2
