#! /bin/bash

set -euf -o pipefail

docker run -it --rm \
  --privileged \
  --volume /dev:/dev \
  --volume /home/tony/proj/clr-sdk:/home/clr/app \
  --volume /home/tony/proj/clr-sdk/mix:/home/clr/mix \
  --id $(id -u):$(id -g) \
  clearlinux:clr-sdk \
  --mixdir=/home/clr/mix
