#! /usr/bin/bash
set -euf -o pipefail

# if running setup.sh
# bash -c '"/tmp/app/setup.sh"'

# REGISTRY=clearlinux
REGISTRY=rg1.tony.wuersch.name:443
# REPO=stacks-dar-mkl
# REPO=mklclr_me_sudo
# REPO=mklclr_rstudio
REPO=mkl-rstudio
# NAME=mklclr
# NAME=mklclr_me_sudo
NAME=mkl-rstudio
# NAME=mklclr_me_sudo

docker run \
  -it --rm --init \
  --env HOME=/home/clr \
  --volume /home/tony/proj/stacks-dars-mkl:/tmp/app \
  --volume /home/tony/docker/volumes/git/git:/tmp/git \
  --volume /home/tony/docker/volumes/tl:/tmp/tl \
  --user 1000:1000 \
  --workdir /home/clr \
  --name $NAME \
  $REGISTRY/$REPO \
  bash -l
